#!/bin/bash
### BEGIN INIT INFO
# Provides:          display_control
# Required-Start:    $network
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: display_control
# Description:       init script for the display_control_sub.js node application
### END INIT INFO

DIR=/home/pi/node
NODE=/usr/local/bin/node
HOSTNAME=`hostname`

test -x $NODE || exit 0

function start_app {
  if [ -f /var/run/display_control.pid ]
  then
    exit 0
  fi
  NODE_ENV=production nohup $NODE $DIR/display_control_sub.js $HOSTNAME 1>>"/var/log/display_control.log" 2>&1 & echo $! > "/var/run/display_control.pid"
}

function stop_app {
  if [ -f /var/run/display_control.pid ]
  then
    sudo kill `cat /var/run/display_control.pid`
    rm /var/run/display_control.pid
  fi
}

case $1 in
   start)
      start_app ;;
    stop)
      stop_app ;;
    restart)
      stop_app
      start_app
      ;;
    *)
      echo "usage: display_control {start|stop}" ;;
esac
exit 0
